export const TERMS_VERSION = "2026-06-10.1";
export const TERMS_EFFECTIVE_DATE = "10 June 2026";

export interface LegalSection {
  id: string;
  heading: string;
  paragraphs: string[];
  bullets?: string[];
}

export const TERMS_SECTIONS: LegalSection[] = [
  {
    id: "acceptance-of-terms",
    heading: "1. Acceptance of Terms",
    paragraphs: [
      "These Terms and Conditions (the \"Terms\") govern your access to and use of Paylo.one (the \"Service\"), operated by Paylo.one (\"we\", \"us\", or \"our\"). By creating an account, accessing the Service, or otherwise using any part of the Service, you agree to be bound by these Terms. If you do not agree to these Terms, you must not use the Service.",
      "If you are using the Service on behalf of a company, organisation, or other legal entity, you represent and warrant that you have the authority to bind that entity to these Terms, in which case \"you\" refers to that entity.",
      "We may update these Terms from time to time as described in the section titled Availability and Changes to the Service. Your continued use of the Service after updated Terms take effect constitutes your acceptance of the updated Terms.",
    ],
  },
  {
    id: "description-of-the-service",
    heading: "2. Description of the Service",
    paragraphs: [
      "Paylo.one is a personal management and knowledge-assistant platform. The Service allows you to create one or more workspaces, connect third-party data sources such as email, calendar, GitHub, WhatsApp, and Notion, and upload your own files and notes. The Service uses artificial intelligence to organise this information and to generate briefings, summaries, and suggested actions.",
      "The Service is provided on a multi-tenant basis. Each workspace operates as a separate tenant, and data belonging to one workspace is logically isolated from data belonging to other workspaces. Access to a workspace is limited to users who have been granted membership of that workspace.",
      "The Service is a productivity and information tool. It is not a substitute for professional legal, financial, medical, or other specialist advice, and outputs produced by the Service should not be relied upon as such.",
    ],
  },
  {
    id: "user-accounts",
    heading: "3. User Accounts",
    paragraphs: [
      "To use the Service you must register for an account and provide accurate, current, and complete information, including a valid email address. You are responsible for keeping your account information up to date.",
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us promptly at [contact email] if you become aware of any unauthorised access to or use of your account.",
      "You must be at least 16 years of age, or the minimum age required in your jurisdiction to consent to use online services, to create an account. We may suspend or terminate accounts that we reasonably believe were created in violation of this requirement.",
    ],
  },
  {
    id: "user-responsibilities",
    heading: "4. User Responsibilities",
    paragraphs: [
      "You are responsible for the data you upload to the Service, the sources you choose to connect, and the way you use outputs generated by the Service. You must ensure that your use of the Service complies with all laws and regulations that apply to you, including data protection and privacy laws.",
      "Where you connect a data source or upload content that contains information about other people, you are responsible for ensuring that you have a lawful basis to process that information and to make it available to the Service.",
      "You agree to use the Service only for its intended purpose and in accordance with these Terms, and to cooperate reasonably with us in investigating any suspected misuse of your account or workspace.",
    ],
  },
  {
    id: "connected-sources-and-third-party-services",
    heading: "5. Connected Sources and Third-Party Services",
    paragraphs: [
      "The Service allows you to connect third-party sources such as email accounts, calendars, GitHub, WhatsApp, and Notion. Data from a third-party source is only ingested into your workspace where you have explicitly connected and approved that source. You may disconnect a source at any time, after which the Service will stop ingesting new data from it.",
      "Credentials and session tokens used to access connected sources are encrypted and stored server-side only. They are never exposed to your browser or to other users, and they are used solely to retrieve data from the sources you have authorised.",
      "Your use of any third-party service remains subject to that service's own terms and policies. We are not responsible for the availability, accuracy, or conduct of third-party services, and connecting a source does not create any relationship between us and the third-party provider on your behalf. If a third-party provider changes or withdraws its interfaces, some integrations may stop working in whole or in part.",
    ],
  },
  {
    id: "user-content-and-uploaded-data",
    heading: "6. User Content and Uploaded Data",
    paragraphs: [
      "\"User Content\" means any data you upload to the Service or that is ingested from your connected sources, including files, notes, messages, events, and metadata. You retain all ownership rights in your User Content. We do not claim ownership of any User Content.",
      "You grant us a limited, worldwide, non-exclusive licence to host, store, process, transmit, and display your User Content solely as necessary to provide, maintain, and improve the Service for you and the members of your workspace. This licence ends when the relevant User Content is deleted from the Service, subject to reasonable backup retention periods.",
      "User Content is stored within your workspace and is subject to tenant isolation. We do not use your User Content to train generalised AI models without your explicit consent.",
      "You represent and warrant that you have all rights necessary to upload and process your User Content through the Service, and that your User Content does not infringe the rights of any third party.",
    ],
  },
  {
    id: "ai-generated-outputs-and-limitations",
    heading: "7. AI-Generated Outputs and Limitations",
    paragraphs: [
      "The Service uses artificial intelligence to generate briefings, summaries, suggested actions, and other outputs (\"AI Outputs\"). AI Outputs are generated automatically from your User Content and connected-source data and are provided for your convenience.",
      "AI Outputs may be incomplete, outdated, or inaccurate, and may occasionally misstate or misattribute information. You should independently verify any AI Output before relying on it or acting on it, particularly where the consequences of an error would be significant.",
      "AI Outputs do not constitute legal, financial, medical, tax, or other professional advice. Suggested actions are proposals only; you remain solely responsible for any action you choose to take, whether or not it was suggested by the Service.",
    ],
  },
  {
    id: "acceptable-use",
    heading: "8. Acceptable Use",
    paragraphs: [
      "You agree not to misuse the Service or assist anyone else in doing so. In particular, you must not:",
    ],
    bullets: [
      "Use the Service for any unlawful purpose or in violation of any applicable law or regulation.",
      "Attempt to access workspaces, data, or accounts belonging to other tenants, or to circumvent tenant isolation or other access controls.",
      "Upload or transmit malware, or content that is unlawful, infringing, or that you do not have the right to process.",
      "Probe, scan, or test the vulnerability of the Service, or interfere with its operation, except as part of an authorised security assessment agreed with us in writing.",
      "Reverse engineer, decompile, or attempt to extract the source code of the Service, except where such restriction is prohibited by law.",
      "Resell, sublicense, or provide the Service to third parties as a service bureau without our prior written consent.",
      "Use the Service to send spam or unsolicited communications, or to harvest personal data about others without a lawful basis.",
      "Use automated means to access the Service at volumes that degrade its performance or exceed reasonable usage limits.",
    ],
  },
  {
    id: "availability-and-changes-to-the-service",
    heading: "9. Availability and Changes to the Service",
    paragraphs: [
      "We aim to keep the Service available and reliable, but we do not guarantee that the Service will be uninterrupted, error-free, or available at any particular time. The Service may be temporarily unavailable due to maintenance, upgrades, or events outside our reasonable control.",
      "We may add, change, or remove features of the Service from time to time. Where a change materially reduces the core functionality of a paid plan, we will use reasonable efforts to notify affected customers in advance.",
      "We may update these Terms to reflect changes to the Service, our business, or applicable law. If we make material changes, we will notify you by email or through the Service before the changes take effect. The version identifier and effective date at the top of these Terms indicate the current revision.",
    ],
  },
  {
    id: "fees-and-subscriptions",
    heading: "10. Fees and Subscriptions",
    paragraphs: [
      "Some features of the Service may be offered free of charge, while others may require a paid subscription. Current pricing, plan features, and billing periods are described within the Service or on our website at the time of purchase.",
      "Subscription fees are billed in advance for the relevant billing period and are non-refundable except where required by law or expressly stated otherwise. Subscriptions renew automatically at the end of each billing period unless cancelled before the renewal date. You may cancel at any time, in which case your subscription remains active until the end of the current billing period.",
      "We may change our fees or introduce new charges with reasonable advance notice. Price changes take effect at the start of your next billing period after the notice. If you do not agree to a price change, you may cancel your subscription before it takes effect.",
      "You are responsible for any taxes, duties, or similar governmental charges associated with your subscription, other than taxes on our income.",
    ],
  },
  {
    id: "intellectual-property",
    heading: "11. Intellectual Property",
    paragraphs: [
      "The Service, including its software, design, user interface, branding, and documentation, is owned by us or our licensors and is protected by intellectual property laws. Except for the limited rights expressly granted in these Terms, we reserve all rights in and to the Service.",
      "Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the Service for your internal purposes during the term of your account.",
      "If you provide feedback, suggestions, or ideas about the Service, you grant us a perpetual, irrevocable, royalty-free licence to use that feedback for any purpose without obligation to you. Feedback does not include your User Content.",
    ],
  },
  {
    id: "disclaimers",
    heading: "12. Disclaimers",
    paragraphs: [
      "The Service is provided on an \"as is\" and \"as available\" basis. To the maximum extent permitted by law, we disclaim all warranties and conditions, whether express, implied, or statutory, including implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement.",
      "Without limiting the foregoing, we do not warrant that the Service will meet your requirements, that AI Outputs will be accurate or complete, that data ingested from connected sources will be complete or current, or that the Service will be free from interruptions, defects, or security incidents.",
      "Some jurisdictions do not allow the exclusion of certain warranties, so some of the exclusions above may not apply to you. Nothing in these Terms excludes or limits any warranty or right that cannot lawfully be excluded or limited.",
    ],
  },
  {
    id: "limitation-of-liability",
    heading: "13. Limitation of Liability",
    paragraphs: [
      "To the maximum extent permitted by law, we will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, revenue, goodwill, data, or business opportunity, arising out of or in connection with these Terms or your use of, or inability to use, the Service, even if we have been advised of the possibility of such damages.",
      "To the maximum extent permitted by law, our total aggregate liability arising out of or in connection with these Terms or the Service will not exceed the amounts you paid to us for the Service in the twelve months preceding the event giving rise to the claim, or one hundred euros if you have not paid any amounts in that period.",
      "Nothing in these Terms excludes or limits liability for death or personal injury caused by negligence, for fraud or fraudulent misrepresentation, or for any other liability that cannot be excluded or limited under applicable law.",
    ],
  },
  {
    id: "termination",
    heading: "14. Termination",
    paragraphs: [
      "You may stop using the Service and delete your account at any time. If you have a paid subscription, deletion of your account does not entitle you to a refund of prepaid fees except where required by law.",
      "We may suspend or terminate your access to the Service, in whole or in part, if you materially breach these Terms, if your use of the Service creates a security or legal risk, or if we are required to do so by law. Where reasonably practicable, we will give you notice and an opportunity to remedy the breach before termination.",
      "Upon termination, your right to use the Service ends and we will delete or anonymise the User Content in your workspace within a reasonable period, subject to backup retention cycles and any legal obligations requiring us to retain certain data. Sections of these Terms that by their nature should survive termination, including provisions on intellectual property, disclaimers, limitation of liability, and governing law, will survive.",
    ],
  },
  {
    id: "governing-law",
    heading: "15. Governing Law",
    paragraphs: [
      "These Terms, and any dispute or claim arising out of or in connection with them or the Service, are governed by the laws of [Jurisdiction], without regard to its conflict of laws principles.",
      "The courts of [Jurisdiction] will have exclusive jurisdiction over any dispute arising out of or in connection with these Terms or the Service, except that nothing in this section deprives you of any mandatory consumer protections or rights to bring proceedings in your place of residence where applicable law grants you such rights.",
    ],
  },
  {
    id: "contact",
    heading: "16. Contact",
    paragraphs: [
      "If you have questions about these Terms or the Service, you can contact us at [contact email] or by post at [company address].",
      "We will use reasonable efforts to respond to enquiries promptly. Formal legal notices under these Terms should be sent in writing to the postal address above.",
    ],
  },
];
