-- ============================================================================
-- 20260613130000_access_and_invitations.sql
-- Beta release plumbing:
--   1. access_requests  — visitors asking for an invitation from the landing
--      page (pre-signup, so NOT tenant-scoped). Written server-side with the
--      service role; reviewed by privileged operators in-app.
--   2. beta_invitations — invitations a beta user sends to other people. Each
--      user has a fixed allowance (5). Tenant-scoped and inviter-owned. The
--      allowance cap is enforced in the application layer (beta-invitations
--      module); the partial unique index below stops duplicate live invites to
--      the same address.
--
-- Conventions mirror the rest of the schema: explicit grants (new tables are
-- not auto-exposed), RLS enabled on every table, end-user reads scoped through
-- auth_tenant_ids() / auth.uid(), and all writes performed server-side with the
-- service role (BYPASSRLS) using explicit predicates.
-- Governance: governance/docs/product/access-and-invitations.md.
-- ============================================================================

-- --- access_requests --------------------------------------------------------
-- A request for access from the marketing landing page. There is no tenant and
-- no signed-in user at this point, so the row is global. Only the service role
-- touches it: the public request-access server action inserts; privileged
-- operators read it through a server-side admin check.
create table public.access_requests (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  email           text not null,
  company_or_role text,
  reason          text,
  status          text not null default 'pending'
                  check (status in ('pending', 'approved', 'declined', 'invited')),
  source          text not null default 'marketing',
  user_agent      text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index access_requests_status_created_idx
  on public.access_requests (status, created_at desc);
create index access_requests_email_idx
  on public.access_requests (lower(email));

-- --- beta_invitations --------------------------------------------------------
-- An invitation sent by a beta user. Inviter-owned and tenant-scoped. Status
-- moves pending -> accepted | expired | revoked. The token backs the invite
-- link and is generated by the application (never guessable).
create table public.beta_invitations (
  id               uuid primary key default gen_random_uuid(),
  tenant_id        uuid not null references public.tenants (id) on delete cascade,
  inviter_user_id  uuid not null references auth.users (id) on delete cascade,
  email            text not null,
  token            text not null unique,
  status           text not null default 'pending'
                   check (status in ('pending', 'accepted', 'expired', 'revoked')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  expires_at       timestamptz not null default (now() + interval '14 days'),
  accepted_at      timestamptz,
  accepted_user_id uuid references auth.users (id) on delete set null
);

create index beta_invitations_tenant_idx
  on public.beta_invitations (tenant_id, created_at desc);
create index beta_invitations_inviter_idx
  on public.beta_invitations (inviter_user_id, created_at desc);

-- One live invitation per address per inviter: a new invite is only allowed
-- once any earlier one is revoked or expired (which frees the allowance slot).
create unique index beta_invitations_live_email_uniq
  on public.beta_invitations (inviter_user_id, lower(email))
  where status in ('pending', 'accepted');

-- --- grants -----------------------------------------------------------------
-- access_requests: service-role only (no end-user surface; admin reads run
-- through the service role after an in-app privileged-role check).
grant all on table public.access_requests to service_role;

-- beta_invitations: authenticated users may read their own invitations
-- (defence in depth); all writes and admin-wide reads go through service_role.
grant select on table public.beta_invitations to authenticated;
grant all on table public.beta_invitations to service_role;

-- --- RLS --------------------------------------------------------------------
alter table public.access_requests  enable row level security;
alter table public.beta_invitations enable row level security;

-- access_requests has no authenticated policy: with no grant + no policy, the
-- table is unreachable except via the service role. RLS is still enabled as a
-- backstop in case a grant is ever added.

-- beta_invitations: a user may read invitations they sent, within a tenant they
-- belong to. Admin-wide reads and every write use the service role.
create policy beta_invitations_inviter_select on public.beta_invitations
  for select to authenticated
  using (
    inviter_user_id = (select auth.uid())
    and tenant_id in (select public.auth_tenant_ids())
  );
